version: '3'
services:
  events-api:
    container_name: events-api
    image: elseff/events-api
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USERNAME=${POSTGRES_USERNAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "SERVER_PORT=${SERVER_PORT}"
    healthcheck:
      test: [ 'CMD', 'curl', '-f','http://localhost:$SERVER_PORT/actuator/health' ]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      events-db:
        condition: service_healthy
  events-db:
    container_name: events-db
    image: postgres:13-alpine
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USERNAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL","sh -c 'pg_isready -U $POSTGRES_USERNAME -d $POSTGRES_DB'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always


