apiVersion: v1
kind: ConfigMap
metadata:
  name: events-api-configmap
  labels:
    app: events-api
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  SERVER_PORT: "8080"
  POSTGRES_USERNAME: "elseff"
  POSTGRES_PASSWORD: "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api-deployment
  labels:
    app: events-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
        - name: events-api-container
          image: elseff/events-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: events-api-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: events-api-configmap
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: events-api-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: events-api-configmap
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: events-api-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: events-api-service
spec:
  selector:
    app: events-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080