name: Deploy

on:
  workflow_run:
    workflows: [ Build ]
    branches:
      - 'master'
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_REPO }} .

      - name: Publish Docker Image
        run: docker push {{ secrets.DOCKER_USERNAME}}/${{ secrets.DOCKER_REPO }}

